name: notification
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  path: any
  sqflite: ^2.4.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  firebase_messaging: ^15.1.3
  get: ^4.6.6
  app_settings: ^5.1.1
  flutter_local_notifications: ^17.2.4
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true